t6x/reaver-wps-fork-t6x

- src/wps/wps_registrar.c
The latest version of Pixiewps in the Kali repository is 1.1. With this version, -r and -S are mutually exclusive and specifying both results in the help message, causing reaver to fail. This commit resolves that problem.
> Pixiewps 1.1 enforces mutual exclusivity with -r and -S options.

- docs/README.REAVER
- docs/README.WASH
- src/wpscrack.c
- src/wpsmon.c
Since the release of **Aircrack-ng v1.2 RC2**, it now uses what was `aircrack-zc` as default for `airmon-ng`. As a result, the interface name has changed for monitor mode from `mon0` to `wlan0mon`.
All places **expect** `README.md` as its been done in #18.
> mon0 -> wlan0mon

- README.md
Dear t6x,
I noticed that the link to the 1.5 repo pointed at the 1.4, so I replaced it with the right one.
Thanks for taking the job where I left it, by the way!
Carles
> Set the right link for the 1.5 version repository

- src/iface.c
Bypass unneeded calculations in next_channel() routine in the case when channel is fixed
> Small code flow optimization

- src/80211.c
The previous patch fixed ath9k, but people report that Ralink throws -01 in RSS.
Now seems work fine
> Ralink -01

- src/argsparser.c
There is a problem in reaver, when you use the -o option to write the stdout to a log file.
If you give it a -o /directory/that/doesnt/exist it crashes with segmentation fault, because its not checking if the file was correctly opened.
The diff below fixes it.
> Fix segmentation fault

- src/crypto/Makefile
this warning here
md5-internal.c:186:5: warning:
dereferencing type-punned pointer will break strict-aliasing rules
[-Wstrict-aliasing]
is serious UB and as such may lead to all kinds of evil compiler behaviour.
fix it by sacrificing a little bit of performance and disabling the
strict aliasing optimization.
> crypto: build with -fno-strict-aliasing

- src/lwe/iwlib.c
- src/lwe/iwlib.h
- src/lwe/wireless.21.h
linux headers tend to be very broken for usage in userspace,
especially when they're using linux/types.h.
clean up the mess by using stdint.h types.
this may be sufficient that the code can be compiled on *BSD.
*NOTE* this was tested on sabotage linux, based on musl libc.
before merging this PR it would be advisable to test this branch
on a GLIBC-based linux distribution and see if it still compiles.
> clean up lwe's use of linux kernel headers

- src/wpsmon.c
the standard unix terminal is 80 characters wide (for example when you
open a new xterm, it will be 80 chars).
wash was very wasteful in its usage and wrapped the output of the header around,
and all ESSIDs that were longer than about 10 chars would be displayed in the
next line. fix it by making the words in the header columns slimmer and
shrinking the whitespace between the columns.
> wash: fit output into 80-char wide terminal

- src/exchange.c
Hi there! A pull request to support additional APs.
Certain APs send empty WPS messages instead of formal NACKs. For example the Belkin F5D7231-4-v3000/ WPS0001.
At present Reaver will hang on M4 indefinitely having failed to recognise this behaviour and expecting additional packets which never arrive:
```
[+] Trying pin ********.
[+] Sending EAPOL START request
[+] Received identity request
[+] Sending identity response
[+] Received M1 message
[+] Sending M2 message
[+] Received M3 message
[+] Sending M4 message
...
```
This patch provides an additional command line option to treat empty WPS messages as NACKs:
`
-M, --empty-message-nack        Treat empty WPS messages as NACKs. Use with -n option. [False]
`
With the desired result:
```
[+] Trying pin ********.
[+] Sending EAPOL START …
```
> Empty WPS messages as NACKs option to cover additional APs

- src/exchange.c
Follow up from https://github.com/t6x/reaver-wps-fork-t6x/pull/119. Minor code tidying for [exchange.c](https://github.com/t6x/reaver-wps-fork-t6x/blob/707c5749a9dae95ec20e947ca8f07f0eda7b4d8f/src/exchange.c) that give us a clearer indication of the code flow in a critical loop section.
Notably:
```c
case TERMINATE:
terminated = 1;
break;
default:
if(packet_type != 0)
{
cprintf(VERBOSE, "[!] WARNING: Unexpected packet received (0x%.02X), terminating transaction\n", packet_type);
terminated = 1;
}
break;
```
to:
```c
case TERMINATE:
terminated = 1;
break;
case UNKNOWN:
// cprintf(VERBOSE, "[+] Received UNKNOWN packet\n");
break;
default:
cprintf(VERBOSE, "[!] WARNING: Unexpected packet received (0x%.02X), terminating transaction\n", packet_type);
terminated = 1;
break;
```
I've left the …
> Minor code tidy/ clarification

- src/Makefile.in
Makefile didn't honour DESTDIR, which is a standard behaviour,
and it failed to produce leading directories.
should fix #84
> Makefile.in: fix behaviour of make install

- README.md
"performances" instead of "performs" in the readme
> Caught a (silly) grammar typo

- src/Makefile.in
They are breaking basic dependencies, like that .o depends on .c,
so are preventing rebuild when .c is changed. Just use implicit
make rule instead.
> Makefile: remove bogus rules

- src/utils/vendor.c
Added vendor OUI 00:09:86 (MetaLink) to detect properly Lantiq WiFi chips such as the "Xwave 300 Lantiq psb8231 11 bgn" from arcadyan ARV7519RW22 (livebox 2.1).
FYI MetaLink was bought by Lantiq in 2010 which explains why they have the same OUI
> vendor.c: Detect Lantiq/MetaLink chipset

- README.md
- src/libwps/libwps.c
- src/libwps/libwps.h
- src/session.c
- src/session.h
- src/wpsmon.c
- src/wpsmon.h
I beleave this option helps the user to choose which router is better to start or to continue the attack.
root@kali:~# wash -i wlan0mon -p
BSSID               Ch  dBm  WPS  Lck  Vendor    ESSID
--------------------------------------------------------------------------------
4C:D0:8A:**:**:**    1  -87  2.0  No   Broadcom  AP-ele (0.04%)
10:C2:5A:**:**:**    1  -83  2.0  No   Broadcom  AP-dinhas 
18:D6:C7:**:**:**    1  -86  1.0  No   AtherosC  AP-RA (21981333)
D4:2C:0F:**:**:**    1  -84  2.0  No   Broadcom  AP-no (0.03%)
E0:41:36:**:**:**    4  -70  1.0  No   RalinkTe  AP-O NPPO (54627345)
74:EA:3A:**:**:**    4  -75  1.0  No   AtherosC  AP-rizsh3 (98107841)
E4:C1:46:**:**:**    6  -83  1.0  No   RealtekS  AP--E3B4 (91.11%)
88:6A:E3:**:**:**    6  -86  2.0  No   RalinkTe  AP-O-3496 …
> wash: show crack progress with -p option

- src/init.c
even though most drivers on linux properly work with rfmon turned on, a few
badly written ones create issues:
issue #202 : rfmon mode causes additional interfaces to appear
issue #265 : issues with RTL8812AU hackjob driver
> activate rfmon only on apple

- src/session.c
Example of a situation:
In the first attempt it fails to complete the authentication, but "m5" is received, so 90.91% is done, and at this point the user sends CTRL+C and nothing has been saved.
As 90.91% is done, then it is good to save in .wpc file.
> save .wpc file if the first half of first pin is correct

- src/session.c
My mistake, the calculation of progress was wrong, correct not need plus 1.
Example of a .wpc file (first 3 lines):
```
1
0
0
```
It's 1/11000 (0.01%) is done and not 2/11000 (0.02%)
Even for:
```
0
999
1
```
It is 10999/11000 (99.99%) is done and not 11000/11000 (100.0%)
removed unnecessary type cast too.
> wash: fix calculation of attack progress

- src/defs.h
Decrease definition of EAPOL_START_MAX_TRIES to speed up the attack.
Often times need to wait 25 times timeout to reassociate.
Decreasing to 10 can save up to 60% of the waiting time until reassociating.
Is number 10 good?
> Decrease definition of EAPOL_START_MAX_TRIES

- src/exchange.c
We forgot to apply retry also for got timeout instead of an M5 message when cracking second half using -J option.
> got timeout instead of an M5 when cracking second half, so retry

- src/cracker.c
- src/cracker.h
- src/exchange.c
I think it is more appropriate to use type int for the variable pin_count.
> stop attack when nack code is SETUP_LOCKED

- src/pins.c
- src/session.c
There is a bug, but it is rare to happen.
To happen, must have the following conditions:
1) pin cracked (12425082)
2) re-attack with only the first half pin (1242)
3) answer yes to restore the previous session
```
reaver -i wlan0mon -b AA:BB:CC:DD:EE:FF -c 1 -vvN -p 1242
```
> fix -p option using new way

- src/exchange.c
Improve the commit 2db7ca59.
After many observations, those routers with modified firmware that avoids PIN attack mode just sends NACK with SETUP_LOCKED reason code (0x000F) only after M2.
Those routers that sends NACK with SETUP_LOCKED reason code after M4/M6 has WPS LOCK temporary, back to unlocked after a short time, but this time increases with each lock.
With -L option ignoring the treatment and continuing the attack.
> Stop attack when nack code is SETUP_LOCKED and last_msg is M1
